sudo: false
addons:
  apt:
    packages:
      - libcap-dev
      - bison
      - git
language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.2.0
  - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=master
  - MRUBY_VERSION=master MRB_CAPABILITY_ENABLE_AMBIENT=1
script:
  - rake clean
  - rake test